/*
 * This file is generated by jOOQ.
*/
package com.franckyi.modcenter.api.jooq;


import com.franckyi.modcenter.api.jooq.tables.Categories;
import com.franckyi.modcenter.api.jooq.tables.Files;
import com.franckyi.modcenter.api.jooq.tables.Optionallibraries;
import com.franckyi.modcenter.api.jooq.tables.Projects;
import com.franckyi.modcenter.api.jooq.tables.Requiredlibraries;
import com.franckyi.modcenter.api.jooq.tables.Versions;
import com.franckyi.modcenter.api.jooq.tables.records.CategoriesRecord;
import com.franckyi.modcenter.api.jooq.tables.records.FilesRecord;
import com.franckyi.modcenter.api.jooq.tables.records.OptionallibrariesRecord;
import com.franckyi.modcenter.api.jooq.tables.records.ProjectsRecord;
import com.franckyi.modcenter.api.jooq.tables.records.RequiredlibrariesRecord;
import com.franckyi.modcenter.api.jooq.tables.records.VersionsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>modcenter</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoriesRecord> KEY_CATEGORIES_PRIMARY = UniqueKeys0.KEY_CATEGORIES_PRIMARY;
    public static final UniqueKey<FilesRecord> KEY_FILES_PRIMARY = UniqueKeys0.KEY_FILES_PRIMARY;
    public static final UniqueKey<OptionallibrariesRecord> KEY_OPTIONALLIBRARIES_PRIMARY = UniqueKeys0.KEY_OPTIONALLIBRARIES_PRIMARY;
    public static final UniqueKey<ProjectsRecord> KEY_PROJECTS_PRIMARY = UniqueKeys0.KEY_PROJECTS_PRIMARY;
    public static final UniqueKey<RequiredlibrariesRecord> KEY_REQUIREDLIBRARIES_PRIMARY = UniqueKeys0.KEY_REQUIREDLIBRARIES_PRIMARY;
    public static final UniqueKey<VersionsRecord> KEY_VERSIONS_PRIMARY = UniqueKeys0.KEY_VERSIONS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CategoriesRecord, ProjectsRecord> CATEGORIES_IBFK_1 = ForeignKeys0.CATEGORIES_IBFK_1;
    public static final ForeignKey<FilesRecord, ProjectsRecord> FILES_IBFK_1 = ForeignKeys0.FILES_IBFK_1;
    public static final ForeignKey<OptionallibrariesRecord, FilesRecord> OPTIONALLIBRARIES_IBFK_1 = ForeignKeys0.OPTIONALLIBRARIES_IBFK_1;
    public static final ForeignKey<OptionallibrariesRecord, ProjectsRecord> OPTIONALLIBRARIES_IBFK_2 = ForeignKeys0.OPTIONALLIBRARIES_IBFK_2;
    public static final ForeignKey<RequiredlibrariesRecord, FilesRecord> REQUIREDLIBRARIES_IBFK_1 = ForeignKeys0.REQUIREDLIBRARIES_IBFK_1;
    public static final ForeignKey<RequiredlibrariesRecord, ProjectsRecord> REQUIREDLIBRARIES_IBFK_2 = ForeignKeys0.REQUIREDLIBRARIES_IBFK_2;
    public static final ForeignKey<VersionsRecord, FilesRecord> VERSIONS_IBFK_1 = ForeignKeys0.VERSIONS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CategoriesRecord> KEY_CATEGORIES_PRIMARY = createUniqueKey(Categories.CATEGORIES, "KEY_categories_PRIMARY", Categories.CATEGORIES.PROJECTID, Categories.CATEGORIES.CATEGORY);
        public static final UniqueKey<FilesRecord> KEY_FILES_PRIMARY = createUniqueKey(Files.FILES, "KEY_files_PRIMARY", Files.FILES.FILEID);
        public static final UniqueKey<OptionallibrariesRecord> KEY_OPTIONALLIBRARIES_PRIMARY = createUniqueKey(Optionallibraries.OPTIONALLIBRARIES, "KEY_optionalLibraries_PRIMARY", Optionallibraries.OPTIONALLIBRARIES.FILEID, Optionallibraries.OPTIONALLIBRARIES.PROJECTID);
        public static final UniqueKey<ProjectsRecord> KEY_PROJECTS_PRIMARY = createUniqueKey(Projects.PROJECTS, "KEY_projects_PRIMARY", Projects.PROJECTS.PROJECTID);
        public static final UniqueKey<RequiredlibrariesRecord> KEY_REQUIREDLIBRARIES_PRIMARY = createUniqueKey(Requiredlibraries.REQUIREDLIBRARIES, "KEY_requiredLibraries_PRIMARY", Requiredlibraries.REQUIREDLIBRARIES.FILEID, Requiredlibraries.REQUIREDLIBRARIES.PROJECTID);
        public static final UniqueKey<VersionsRecord> KEY_VERSIONS_PRIMARY = createUniqueKey(Versions.VERSIONS, "KEY_versions_PRIMARY", Versions.VERSIONS.FILEID, Versions.VERSIONS.VERSION);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CategoriesRecord, ProjectsRecord> CATEGORIES_IBFK_1 = createForeignKey(com.franckyi.modcenter.api.jooq.Keys.KEY_PROJECTS_PRIMARY, Categories.CATEGORIES, "categories_ibfk_1", Categories.CATEGORIES.PROJECTID);
        public static final ForeignKey<FilesRecord, ProjectsRecord> FILES_IBFK_1 = createForeignKey(com.franckyi.modcenter.api.jooq.Keys.KEY_PROJECTS_PRIMARY, Files.FILES, "files_ibfk_1", Files.FILES.PROJECTID);
        public static final ForeignKey<OptionallibrariesRecord, FilesRecord> OPTIONALLIBRARIES_IBFK_1 = createForeignKey(com.franckyi.modcenter.api.jooq.Keys.KEY_FILES_PRIMARY, Optionallibraries.OPTIONALLIBRARIES, "optionalLibraries_ibfk_1", Optionallibraries.OPTIONALLIBRARIES.FILEID);
        public static final ForeignKey<OptionallibrariesRecord, ProjectsRecord> OPTIONALLIBRARIES_IBFK_2 = createForeignKey(com.franckyi.modcenter.api.jooq.Keys.KEY_PROJECTS_PRIMARY, Optionallibraries.OPTIONALLIBRARIES, "optionalLibraries_ibfk_2", Optionallibraries.OPTIONALLIBRARIES.PROJECTID);
        public static final ForeignKey<RequiredlibrariesRecord, FilesRecord> REQUIREDLIBRARIES_IBFK_1 = createForeignKey(com.franckyi.modcenter.api.jooq.Keys.KEY_FILES_PRIMARY, Requiredlibraries.REQUIREDLIBRARIES, "requiredLibraries_ibfk_1", Requiredlibraries.REQUIREDLIBRARIES.FILEID);
        public static final ForeignKey<RequiredlibrariesRecord, ProjectsRecord> REQUIREDLIBRARIES_IBFK_2 = createForeignKey(com.franckyi.modcenter.api.jooq.Keys.KEY_PROJECTS_PRIMARY, Requiredlibraries.REQUIREDLIBRARIES, "requiredLibraries_ibfk_2", Requiredlibraries.REQUIREDLIBRARIES.PROJECTID);
        public static final ForeignKey<VersionsRecord, FilesRecord> VERSIONS_IBFK_1 = createForeignKey(com.franckyi.modcenter.api.jooq.Keys.KEY_FILES_PRIMARY, Versions.VERSIONS, "versions_ibfk_1", Versions.VERSIONS.FILEID);
    }
}
