/*
 * This file is generated by jOOQ.
*/
package com.franckyi.modcenter.api.jooq;


import com.franckyi.modcenter.api.jooq.tables.Categories;
import com.franckyi.modcenter.api.jooq.tables.Files;
import com.franckyi.modcenter.api.jooq.tables.Optionallibraries;
import com.franckyi.modcenter.api.jooq.tables.Projects;
import com.franckyi.modcenter.api.jooq.tables.Requiredlibraries;
import com.franckyi.modcenter.api.jooq.tables.Versions;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in modcenter
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>modcenter.categories</code>.
     */
    public static final Categories CATEGORIES = com.franckyi.modcenter.api.jooq.tables.Categories.CATEGORIES;

    /**
     * The table <code>modcenter.files</code>.
     */
    public static final Files FILES = com.franckyi.modcenter.api.jooq.tables.Files.FILES;

    /**
     * The table <code>modcenter.optionalLibraries</code>.
     */
    public static final Optionallibraries OPTIONALLIBRARIES = com.franckyi.modcenter.api.jooq.tables.Optionallibraries.OPTIONALLIBRARIES;

    /**
     * The table <code>modcenter.projects</code>.
     */
    public static final Projects PROJECTS = com.franckyi.modcenter.api.jooq.tables.Projects.PROJECTS;

    /**
     * The table <code>modcenter.requiredLibraries</code>.
     */
    public static final Requiredlibraries REQUIREDLIBRARIES = com.franckyi.modcenter.api.jooq.tables.Requiredlibraries.REQUIREDLIBRARIES;

    /**
     * The table <code>modcenter.versions</code>.
     */
    public static final Versions VERSIONS = com.franckyi.modcenter.api.jooq.tables.Versions.VERSIONS;
}
