/*
 * This file is generated by jOOQ.
*/
package com.franckyi.modcenter.api.jooq.tables.records;


import com.franckyi.modcenter.api.jooq.tables.Files;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilesRecord extends UpdatableRecordImpl<FilesRecord> implements Record8<Integer, String, String, String, Date, Integer, String, Integer> {

    private static final long serialVersionUID = -1412223929;

    /**
     * Setter for <code>franckyi_modcenter.files.fileId</code>.
     */
    public void setFileid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.fileId</code>.
     */
    public Integer getFileid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>franckyi_modcenter.files.fileName</code>.
     */
    public void setFilename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.fileName</code>.
     */
    public String getFilename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>franckyi_modcenter.files.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>franckyi_modcenter.files.size</code>.
     */
    public void setSize(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.size</code>.
     */
    public String getSize() {
        return (String) get(3);
    }

    /**
     * Setter for <code>franckyi_modcenter.files.uploaded</code>.
     */
    public void setUploaded(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.uploaded</code>.
     */
    public Date getUploaded() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>franckyi_modcenter.files.downloads</code>.
     */
    public void setDownloads(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.downloads</code>.
     */
    public Integer getDownloads() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>franckyi_modcenter.files.fileUrl</code>.
     */
    public void setFileurl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.fileUrl</code>.
     */
    public String getFileurl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>franckyi_modcenter.files.projectId</code>.
     */
    public void setProjectid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.files.projectId</code>.
     */
    public Integer getProjectid() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Date, Integer, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Date, Integer, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Files.FILES.FILEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Files.FILES.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Files.FILES.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Files.FILES.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Files.FILES.UPLOADED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Files.FILES.DOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Files.FILES.FILEURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Files.FILES.PROJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFileid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getUploaded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFileurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value1(Integer value) {
        setFileid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value2(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value4(String value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value5(Date value) {
        setUploaded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value6(Integer value) {
        setDownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value7(String value) {
        setFileurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord value8(Integer value) {
        setProjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilesRecord values(Integer value1, String value2, String value3, String value4, Date value5, Integer value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilesRecord
     */
    public FilesRecord() {
        super(Files.FILES);
    }

    /**
     * Create a detached, initialised FilesRecord
     */
    public FilesRecord(Integer fileid, String filename, String type, String size, Date uploaded, Integer downloads, String fileurl, Integer projectid) {
        super(Files.FILES);

        set(0, fileid);
        set(1, filename);
        set(2, type);
        set(3, size);
        set(4, uploaded);
        set(5, downloads);
        set(6, fileurl);
        set(7, projectid);
    }
}
