/*
 * This file is generated by jOOQ.
*/
package com.franckyi.modcenter.api.jooq.tables.records;


import com.franckyi.modcenter.api.jooq.tables.Projects;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectsRecord extends UpdatableRecordImpl<ProjectsRecord> implements Record8<Integer, String, String, Integer, Date, String, String, String> {

    private static final long serialVersionUID = -12163380;

    /**
     * Setter for <code>franckyi_modcenter.projects.projectId</code>.
     */
    public void setProjectid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.projectId</code>.
     */
    public Integer getProjectid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>franckyi_modcenter.projects.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>franckyi_modcenter.projects.author</code>.
     */
    public void setAuthor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.author</code>.
     */
    public String getAuthor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>franckyi_modcenter.projects.totalDl</code>.
     */
    public void setTotaldl(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.totalDl</code>.
     */
    public Integer getTotaldl() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>franckyi_modcenter.projects.updated</code>.
     */
    public void setUpdated(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.updated</code>.
     */
    public Date getUpdated() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>franckyi_modcenter.projects.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>franckyi_modcenter.projects.projectUrl</code>.
     */
    public void setProjecturl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.projectUrl</code>.
     */
    public String getProjecturl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>franckyi_modcenter.projects.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>franckyi_modcenter.projects.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Date, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Date, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Projects.PROJECTS.PROJECTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Projects.PROJECTS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Projects.PROJECTS.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Projects.PROJECTS.TOTALDL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Projects.PROJECTS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Projects.PROJECTS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Projects.PROJECTS.PROJECTURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Projects.PROJECTS.THUMBNAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTotaldl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProjecturl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value1(Integer value) {
        setProjectid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value3(String value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value4(Integer value) {
        setTotaldl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value5(Date value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value7(String value) {
        setProjecturl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord value8(String value) {
        setThumbnail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectsRecord values(Integer value1, String value2, String value3, Integer value4, Date value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectsRecord
     */
    public ProjectsRecord() {
        super(Projects.PROJECTS);
    }

    /**
     * Create a detached, initialised ProjectsRecord
     */
    public ProjectsRecord(Integer projectid, String name, String author, Integer totaldl, Date updated, String description, String projecturl, String thumbnail) {
        super(Projects.PROJECTS);

        set(0, projectid);
        set(1, name);
        set(2, author);
        set(3, totaldl);
        set(4, updated);
        set(5, description);
        set(6, projecturl);
        set(7, thumbnail);
    }
}
